services:
  electronicvoting.validator_a:
    image: electronicvoting.validator
    build:
      context: .
      dockerfile: ElectronicVoting.Validator/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - RabbitMQ__Host=rabbitmq_a
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ConnectionStrings__ElectionDb=Host=election-db;Port=5432;Database=election;Username=user;Password=pass
      - ConnectionStrings__ValidatorDb=Host=validator-db-a;Port=5432;Database=validator-db-a;Username=user;Password=pass
      - Validator__PrivateKeyForVoteSigning=-----BEGIN PRIVATE KEY-----\nMIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQDPDjTlD0x3cJdi\napxuAPyRGDdYPyp1XfD9cOs5+IsZl1Lt0dzRTSd/qeVz7qtceUTIBdxgjnzIRiwo\n5FHZj7gv6ItwKMYdXa6MVLELhH3EqMIp60gpkqg16bhHVfbdVuXC4xUsoIuKiyHy\nSlLYXt+Sp1vZ1MRvN5rYcFAGzaeD4dA7p2iSgYnISBglfSm1l4YkL5x48fuOLOA2\nVFIvHrQqGuIcKPTSAsXZ4AcI6MecQf3+qxPP4HWieps3dUdCyKvff2jqd3xjvFUc\nSIWSZBb3LeWs1xFJOnI3bQahVQYYYtLDhls2gcyH1S1YQor7aHrnoaJYCOJJLnQd\ncLPqupv9AgMBAAECgf9++zd1QuyiU2qD8N3+mJxMX42RkSt4zyP8SkP4SXUFPMif\nERVbRvXyVT9i2fw9uiF0iiOdE8VzDZYHff60bm+G8haRsm/NkqZ5aXcqmRaIhPaO\nvryCwm5moe9h0FaVZ7WAz8Msm0j4rlsjPHGSQJzcU8cA0HunuXI9SqPJiFYzii6z\nvYlj3RkgZ8RNSubH9jGRleJhbtECnTIdlrEx2Tc8HBXKd+wWqDP+NasI/WU2H5ly\nWxHrJomIZZYRqSQEqCucUDeprWgCYtWZRgnzza14CKKrw1I89A9N0xLzSWRekpzs\nbT/DNNJqWmgIF/aUvsxpyBe9MPxZCgbNHA1A4k0CgYEA63SOrONcMRyay3SB3IoN\nDzk1uVoWhrlURaW0RHcAtFooeqc+bJaRD+Z5NdZffy6leMW9ShvdD1fq7z2KuyeR\n6R9pXganojLu2nbR3vPS+tua0pIJajKOf93C/wyYiFR2JZ0c6alzIqQX5G5k3sCQ\nlbuvIV8cWS1bOjzIxMQAsE8CgYEA4R9F//SblQSJmc48MVSHPp0Rm248+C90zY23\nMfHvrIRo6hCMbTwhVlFNR9SFUeIqsFF16d4McJdOQTq8jKFAPJtsvkq1poXuWG3Z\nE3/X0+sgw7Aqm6w8lPzpAW0DrZzZI19qyuyEvhK9k0rikqvUA+TjAPBO0Zr4HmsI\nYLMPb/MCgYA+xKjQYCAQm56MhHemEkte9pJi4ihFLBzSIFWJNuxCKBLId9NFYXI0\nee1wM8Drh8TnCFfo7Lqmv3pK4u4b7HWSXyRYw49mxwszxB84v2lMJMUGQ5Ys8GNa\npQS5t2LmXRXN+y9c/yZJYtNXuzI6y7z/nbQXQmKtR1EdmlyvT80bMwKBgB3u1JXl\n5lH4Gnuy6ln8zUbMB61NCRpO5Q73yuX/L0kXCgQlUyarGhuqD8Z/QYLTua1cB3uj\nJLBLzgHqV2uzfSER4XGj6WdM45YqdPScyQvKdb7PS7sLObrtreWcoyKQemazpzV4\nIWZMg5x0FpA9/KDP7EcRrMk9+8O/o4uIA4N1AoGBANgdYd+cR9N/biwpFuhSDeRk\nCtdB4uZecgocNudPYzEZtfmnVN1xZ6sqKa4JUTJ1xEfoB+vFVUOHxSlRVeXl1y0r\nThCRmV9wFJ4ysL4J2Ru9cT8mSrsdZv0xmioXKZQ+6UY9a7zyip+ON8uojCjgyLzT\nkcaq+DZtOVMU+BKBw2eR\n-----END PRIVATE KEY-----\n
      - Validator__Name=electronicvoting.validator_a
    depends_on:
      validator-db-a:
        condition: service_healthy
      election-db:
        condition: service_healthy
      rabbitmq_a:
        condition: service_healthy

    networks:
      - voting-net

  validator-db-a:
    image: postgres:16
    container_name: validator-db-a
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=validator-db-a
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d election" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - voting-net
        
  election-db:
    image: postgres:16
    restart: always
    container_name: election-db
    environment:
      POSTGRES_DB: election
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d election" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - voting-net

  rabbitmq_a:
    image: rabbitmq:3-management
    container_name: rabbitmq_a
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - voting-net
        
  electronicvoting.validator_b:
    image: electronicvoting.validator
    build:
      context: .
      dockerfile: ElectronicVoting.Validator/Dockerfile
    ports:
      - "5001:8080"
      - "5002:8081"
    environment:
      - RabbitMQ__Host=rabbitmq_b
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ConnectionStrings__ElectionDb=Host=election-db;Port=5432;Database=election;Username=user;Password=pass
      - ConnectionStrings__ValidatorDb=Host=validator-db-b;Port=5432;Database=validator-db-b;Username=user;Password=pass
      - Validator__PrivateKeyForVoteSigning=-----BEGIN PRIVATE KEY-----\nMIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQDPDjTlD0x3cJdi\napxuAPyRGDdYPyp1XfD9cOs5+IsZl1Lt0dzRTSd/qeVz7qtceUTIBdxgjnzIRiwo\n5FHZj7gv6ItwKMYdXa6MVLELhH3EqMIp60gpkqg16bhHVfbdVuXC4xUsoIuKiyHy\nSlLYXt+Sp1vZ1MRvN5rYcFAGzaeD4dA7p2iSgYnISBglfSm1l4YkL5x48fuOLOA2\nVFIvHrQqGuIcKPTSAsXZ4AcI6MecQf3+qxPP4HWieps3dUdCyKvff2jqd3xjvFUc\nSIWSZBb3LeWs1xFJOnI3bQahVQYYYtLDhls2gcyH1S1YQor7aHrnoaJYCOJJLnQd\ncLPqupv9AgMBAAECgf9++zd1QuyiU2qD8N3+mJxMX42RkSt4zyP8SkP4SXUFPMif\nERVbRvXyVT9i2fw9uiF0iiOdE8VzDZYHff60bm+G8haRsm/NkqZ5aXcqmRaIhPaO\nvryCwm5moe9h0FaVZ7WAz8Msm0j4rlsjPHGSQJzcU8cA0HunuXI9SqPJiFYzii6z\nvYlj3RkgZ8RNSubH9jGRleJhbtECnTIdlrEx2Tc8HBXKd+wWqDP+NasI/WU2H5ly\nWxHrJomIZZYRqSQEqCucUDeprWgCYtWZRgnzza14CKKrw1I89A9N0xLzSWRekpzs\nbT/DNNJqWmgIF/aUvsxpyBe9MPxZCgbNHA1A4k0CgYEA63SOrONcMRyay3SB3IoN\nDzk1uVoWhrlURaW0RHcAtFooeqc+bJaRD+Z5NdZffy6leMW9ShvdD1fq7z2KuyeR\n6R9pXganojLu2nbR3vPS+tua0pIJajKOf93C/wyYiFR2JZ0c6alzIqQX5G5k3sCQ\nlbuvIV8cWS1bOjzIxMQAsE8CgYEA4R9F//SblQSJmc48MVSHPp0Rm248+C90zY23\nMfHvrIRo6hCMbTwhVlFNR9SFUeIqsFF16d4McJdOQTq8jKFAPJtsvkq1poXuWG3Z\nE3/X0+sgw7Aqm6w8lPzpAW0DrZzZI19qyuyEvhK9k0rikqvUA+TjAPBO0Zr4HmsI\nYLMPb/MCgYA+xKjQYCAQm56MhHemEkte9pJi4ihFLBzSIFWJNuxCKBLId9NFYXI0\nee1wM8Drh8TnCFfo7Lqmv3pK4u4b7HWSXyRYw49mxwszxB84v2lMJMUGQ5Ys8GNa\npQS5t2LmXRXN+y9c/yZJYtNXuzI6y7z/nbQXQmKtR1EdmlyvT80bMwKBgB3u1JXl\n5lH4Gnuy6ln8zUbMB61NCRpO5Q73yuX/L0kXCgQlUyarGhuqD8Z/QYLTua1cB3uj\nJLBLzgHqV2uzfSER4XGj6WdM45YqdPScyQvKdb7PS7sLObrtreWcoyKQemazpzV4\nIWZMg5x0FpA9/KDP7EcRrMk9+8O/o4uIA4N1AoGBANgdYd+cR9N/biwpFuhSDeRk\nCtdB4uZecgocNudPYzEZtfmnVN1xZ6sqKa4JUTJ1xEfoB+vFVUOHxSlRVeXl1y0r\nThCRmV9wFJ4ysL4J2Ru9cT8mSrsdZv0xmioXKZQ+6UY9a7zyip+ON8uojCjgyLzT\nkcaq+DZtOVMU+BKBw2eR\n-----END PRIVATE KEY-----\n
      - Validator__Name=electronicvoting.validator_b
    depends_on:
      validator-db-b:
        condition: service_healthy
      election-db:
        condition: service_healthy
      rabbitmq_b:
        condition: service_healthy
    networks:
      - voting-net

  validator-db-b:
    image: postgres:16
    container_name: validator-db-b
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=validator-db-b 
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d election" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - voting-net
      
  rabbitmq_b:
    image: rabbitmq:3-management
    container_name: rabbitmq_b
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - voting-net
      
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "MINIO_ACCESS_KEY"       
      MINIO_ROOT_PASSWORD: "MINIO_SECRET_KEY"   
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - voting-net

networks:
  voting-net:
    external: true
    
volumes:
  minio_data:
